{{- if .Values.externalSecret.enabled }}
apiVersion: {{ .Values.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "generic-app.fullname" . }}
  namespace: {{ include "generic-app.namespace" . | quote }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
    {{- if .Values.externalSecret.labels }}
    {{- include "generic-app.tplvalues.render" (dict "value" .Values.externalSecret.labels "context" $) | nindent 4 }}
    {{- end }}
  {{- if or .Values.externalSecret.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.externalSecret.annotations }}
    {{- include "generic-app.tplvalues.render" (dict "value" .Values.externalSecret.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "generic-app.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ default (include "generic-app.fullname" .) .Values.externalSecret.target.name }}
    creationPolicy: {{ .Values.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.externalSecret.target.deletionPolicy }}
    {{- if .Values.externalSecret.target.template }}
    template: {{- include "generic-app.tplvalues.render" (dict "value" .Values.externalSecret.target.template "context" $) | nindent 6 }}
    {{- end }}
  {{- if .Values.externalSecret.data }}
  data: {{- include "generic-app.tplvalues.render" (dict "value" .Values.externalSecret.data "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.externalSecret.dataFrom }}
  dataFrom: {{- include "generic-app.tplvalues.render" (dict "value" .Values.externalSecret.dataFrom "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
