{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "generic-app.fullname" . }}
  namespace: {{ include "generic-app.namespace" . | quote }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "generic-app.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ include "generic-app.namespace" . | quote }}
  {{- if .Values.serviceMonitor.jobLabel }}
  jobLabel: {{ .Values.serviceMonitor.jobLabel | quote }}
  {{- end }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port | quote }}
      path: {{ .Values.serviceMonitor.path | quote }}
      {{- if .Values.serviceMonitor.interval }}
      interval: {{ .Values.serviceMonitor.interval | quote }}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout | quote }}
      {{- end }}
      {{- if .Values.serviceMonitor.scheme }}
      scheme: {{ .Values.serviceMonitor.scheme | quote }}
      {{- end }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings: {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
{{- end }}
